package com.sugar;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTRY.
 */
public class Entry {

    private Long id;
    private String description;
    private Double sugar_amount;
    private Long date;

    public Entry() {
    }

    public Entry(Long id) {
        this.id = id;
    }

    public Entry(Long id, String description, Double sugar_amount, Long date) {
        this.id = id;
        this.description = description;
        this.sugar_amount = sugar_amount;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Double getSugar_amount() {
        return sugar_amount;
    }

    public void setSugar_amount(Double sugar_amount) {
        this.sugar_amount = sugar_amount;
    }

    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

}
